version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}

  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - /home/ubuntu/plex/library:/config
      - /home/ubuntu/plex/tvshows:/tv
      - /home/ubuntu/plex/home_videos:/home_vids
      - /home/ubuntu/plex/movies:/movies

#  qbittorrent:
#    image: linuxserver/qbittorrent
#    container_name: qbittorrent
#    network_mode: "service:pia"
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - UMASK_SET=022
#      - WEBUI_PORT=8080
#    volumes:
#      - /home/ubuntu/docker:/config
#      - /home/ubuntu/Downloads:/downloads
#    ports:
#      - 6881:6881
#      - 6881:6881/udp
#      - 8080:8080
#    restart: always

#  pia-vpn:
#    container_name: pia-vpn
#    image: itsdaspecialk/pia-openvpn
#    restart: always
#    cap_add:
#      - net_admin
#    dns:
#      - 209.222.18.222
#      - 209.222.18.218
#    ports:
#      - 9091:9091
#    environment:
#      - REGION=US East
#      - USERNAME=p0554771
#      - PASSWORD=sj7rktWTra

  transmission-openvpn:
    container_name: transmission_vpn
    restart: always
    volumes:
        - /home/ubuntu/transmission_vpn:/data
        - /etc/localtime:/etc/localtime:ro
        - /home/ubuntu/docker/transmission_vpn:/config
        - /home/ubuntu/plex/tvshows:/tv
        - /home/ubuntu/plex/movies:/movies
    environment:
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=US California
        - OPENVPN_USERNAME=p0554771
        - OPENVPN_PASSWORD=sj7rktWTra
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.0.0/24
        - PUID=${PUID}
        - PGID=${PGID}
        - WEBPROXY_ENABLED=true
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
    image: haugene/transmission-openvpn
